[package]
org = "hp"
name = "backend"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = false

[dependencies]
# Force latest HTTP module (not 2.12.9)
"ballerina/http" = "2.14.0"
